namespace SimpleE_commerceAPI.Application.Common.Models
{
    public class CreateOrderModel
    {
        public string PaymentMethod { get; set; } // "Stripe", "PayPal"
        public string PaymentToken { get; set; } // The token generated by payment SDK
        public string ShippingAddress { get; set; }
    }
}
